# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029ac5cbf3c138f2a9b694ebcc410c788ddb89792a9b37b1ada8d7d4800826c378d3299d54a0e4c7d24eb27c9dcfc8a7c23f62386d729f2fc2411d2985bc26de

test:
  secret_key_base: 4b7862a0847e2eabda743510bfd9226751ce763a831da560cc10d97bb091f68816559c50865842e2fa53a08d782c3f7d1a90bc32d70cf1c651d51aa0e39749ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
